language: python
python:
  - "3.6"
addons:
  apt:
    packages:
    - gfortran
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libgmp-dev
    - libmpfr-dev
before_install:
  - sudo pip install Cython
  - pip install -U --only-binary=numpy,scipy numpy scipy
install: make
script: nosetests -v test/test.py
notifications:
  email: false